engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
      argument-count:
        config:
          threshold: 4
      complex-logic:
        config:
          threshold: 4
      file-lines:
        config:
          threshold: 250
      method-complexity:
        config:
          threshold: 5
      method-count:
        config:
          threshold: 20
      method-lines:
        enabled: false
      nested-control-flow:
        config:
          threshold: 4
      return-statements:
        enabled: false
      identical-code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- node_modules/
- client/
- server/src/models/
- server/src/migrations/
- server/test/
- template/
- .nyc_output
- coverage