language: node_js

node_js:
  - "8.2.1"

script:
  - NODE_ENV=development npm test
  - npm run jest

install:
  - npm install
  - npm install -g codecov
env:
  

services:
  - postgresql

cache:
  directories:
   - "node_modules"

before_script:
  - psql -c "create database events_manager_test;" -U postgres
  - psql -c "create database events_manager;" -U postgres
  - NODE_ENV=development npm run seq:create 
  - npm install -g nyc
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_success:
  - NODE_ENV=development npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - npm run jest
  