language: node_js

node_js:
  - "8.2.1"

script:
  - NODE_ENV=test && npm test
env:
  - TEST_DBURL=process.env.DB_TEST_URL

install:
  - npm install
cache:
  directories:
   - "node_modules"

services:
  - postgresql

before_script:
  - psql -c "create database events_manager_test;" -U postgres

after_success:
  - NODE_ENV=test && npm run coverage