language: node_js

node_js:
  - "8.2.1"

script:
  - npm run seq:create
  - npm test

install:
  - npm install
cache:
  directories:
   - "node_modules"

services:
  - postgresql

before_script:
  - psql -c "create database events_manager;" -U postgres

after_success:
  - npm run coverage