language: node_js

node_js:
  - "8.2.1"

script:
  - NODE_ENV=test && npm test

install:
  - npm install

env:
  - NODE_ENV=test
services:
  - postgresql

before_script:
  - "NODE_ENV=test"
  - psql -c "create database events_manager_test;" -U postgres

after_success:
  - npm run coverage